<?php
/**
 * @file
 * Token Entity render module.
 */

use Drupal\Core\Render\BubbleableMetadata;
use Html2Text\Html2Text;

/**
 * Implements hook_token_info().
 */
function token_entity_render_token_info() {
  $tokens = array();
  $entities = entity_get_info();
  foreach ($entities as $entity) {
    $tokens[$entity['token type']] = array(
      'render' => array(
        'name' => t('Rendered @type', array('@type' => $entity['label'])),
        'description' => t('Renders a @type using the pattern [@label:render:?], where ? stands for the view mode name.',
          array(
            '@label' => $entity['token type'],
            '@type' => $entity['label']
          )),
      ),
      'render_text' => array(
        'name' => t('Rendered @type (html stripped)', array('@type' => $entity['label'])),
        'description' => t('Text renders a @type using the pattern [@label:render:?], where ? stands for the view mode name.',
          array(
            '@label' => $entity['token type'],
            '@type' => $entity['label']
          )),
      ),
    );
  }
  return array(
    'tokens' => $tokens,
  );
}

/**
 * Implements hook_tokens().
 */
function token_entity_render_tokens($type, $tokens, array $data = [], array $options = [], BubbleableMetadata $bubbleable_metadata) {
  $replacements = [];
  $langcode = !empty($options['language']->language) ? $options['language']->language : NULL;

  foreach ($tokens as $name => $original) {
    $parts = explode(':', $name);
    if ($parts[0] == 'render' || $parts[0] == 'render_text') {
      $view_mode = 'full';

      $entity = $data['entity'];
      $entity_type = $entity->getEntityTypeId();
      $render_controller = \Drupal::entityManager()->getViewBuilder($entity_type);

      if (isset($parts[1])) {
        $available_view_modes = Drupal::entityQuery('entity_view_mode')
          ->condition('targetEntityType', $entity_type)
          ->execute();
        if (isset($available_view_modes[$parts[1]])) {
          $view_mode = $parts[1];
        }
      }

      $rendered_entity = $render_controller->view($entity, $view_mode, $langcode);

      if ($parts[0] == 'render_text') {
        // convert html to txt
        $rendered_entity = Html2Text::convert($rendered_entity);
      }

      $replacements[$original] = drupal_render($rendered_entity);
    }
  }

  return $replacements;
}
